django_auth/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        '', 
         views.home, 
         name='home'
    ),
    path(
        'login/', 
         auth_views.LoginView.as_view(), 
         name='login'
         ),
    path(
        'logout/', 
         auth_views.LogoutView.as_view(), 
         name='logout'
         ),
    path(
        'private_page_one/', 
         views.private_page_one, 
         name='private_page_one'
         ),
    path(
        'private_page_two/', 
         views.private_page_two, 
         name='private_page_two'
         ),
    path(
        'password_change/', 
         auth_views.PasswordChangeView.as_view(success_url='/accounts/password_change_done'), 
         name='password_change'
         ),
    path(
        'password_change_done/', 
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'
         ),
    path(
        'password_reset/', 
         auth_views.PasswordResetView.as_view(success_url='/accounts/password_reset_done'), 
         name='password_reset'
         ),
    path(
        'password_reset_done/', 
         auth_views.PasswordResetDoneView.as_view(), 
         name='password_reset_done'
         ),
    path(
        'password_reset_confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(success_url='/accounts/password_reset_complete'), 
         name='password_reset_confirm'
         ),
    path(
        'password_reset_complete/', 
         auth_views.PasswordResetCompleteView.as_view(), 
         name='password_reset_complete'
         ),
    path(
        'register/', 
         views.register, 
         name='register'
         ),
]

django_auth/django_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='accounts/', permanent=False)),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

django_auth/accounts/models.py
from django.db import models

# Create your models here.

django_auth/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginUserForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def save(self, commit = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

django_auth/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from .forms import UserRegistrationForm, LoginUserForm

def home(request):
    return render(request, 'accounts/home.html')
@login_required
def private_page_one(request):
    return render(request, 'accounts/private_page_one.html')

@login_required
def private_page_two(request):
    return render(request, 'accounts/private_page_two.html')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

django_auth/accounts/templates/accounts/actions.html
<style>
    .button-container {
        display: flex;
        gap: 10px;
    }
</style>

<div class="button-container">
    <p>
        <a href="{% url 'accounts:private_page_one' %}"><input type="button" value="private_page_one"></a>
    </p>
    <p>
        <a href="{% url 'accounts:private_page_two' %}"><input type="button" value="private_page_two"></a>
    </p>
    <p>
        <a href="{% url 'accounts:password_change' %}"><input type="button" value="password_change"></a>
    </p>
</div>

<p>
    <form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
</p>

django_auth/accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome Django Auth System</h1>
    <p>Please choose an option:</p>
    <ul>
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:register' %}">Register</a></li>
    </ul>
</body>
</html>

django_auth/accounts/templates/accounts/login_user.html
<h1>Login page</h1>

<h5>{{ error_message }}</h5>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next_url }}"/>
    <button type="submit">Login</button>
</form>

django_auth/accounts/templates/accounts/private_page_one.html
<h1>Private page one.</h1>

<hr>
<p>
    <strong>Username</strong>:{{ user.username }}
</p>
<p>
    <strong>Email</strong>:{{ user.email }}
</p>
<p>
    <strong>Password</strong>:{{ user.password }}
</p>

{% include 'accounts/actions.html' %}

django_auth/accounts/templates/accounts/private_page_two.html
<h1>Private page two.</h1>

{% include 'accounts/actions.html' %}